name: Test 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - name: install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "PATH=${PATH}:$HOME/.poetry/bin" >> $GITHUB_ENV
        poetry --version
    - name: checkout main branch
      uses: actions/checkout@main
    # Runs a single command using the runners shell
    - name: poe
      run: |
        poetry install
        poetry run mypy tmp.py
    - name: Run a one-line script
      run: python tmp.py
      
    
