name: Sand 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: update python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: aws credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: check
      run: aws iam list-attached-user-policies --user-name lambda-github-actions
